### PR TITLE
Update docker-compose.yaml

### PR DESCRIPTION
**Pull request by diego-vieira**
fix mysql host

```
traduora_1  | [Nest] 1   - 3/11/2019, 10:36:30 AM   [ExceptionHandler] getaddrinfo ENOTFOUND mysql mysql:3306 +2ms
traduora_1  | Error: getaddrinfo ENOTFOUND mysql mysql:3306
traduora_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
traduora_1  |     --------------------
traduora_1  |     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
traduora_1  |     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
traduora_1  |     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:118:18)
traduora_1  |     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
traduora_1  |     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:700:18
traduora_1  |     at new Promise (<anonymous>)
traduora_1  |     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:697:16)
traduora_1  |     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:253:51)
traduora_1  |     at step (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:32:23)
traduora_1  |     at Object.next (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:13:53)
traduora_traduora_1 exited with code 139
````

### CODE REVIEW

**Comment by anthonynsimon** [comment]
Thank you!

**Comment by anthonynsimon** [comment]
@diego-vieira by the way, would you mind signing traduora's contributor license agreement?

It does not change your rights to use your own contributions for any other purpose, it's simply to ensure that we can distribute your code without restriction (i.e. if we wanted to change the license in the future to a more permissive one like Apache 2.0).

You can find it [here](https://goo.gl/forms/zjAKBr8gfUOvR83D2).

Let me know if you have any questions :)

**Comment by diego-vieira** [comment]
That's all done 👍 

Happy to help with the translation to Brazilian Portuguese when the time comes.

**Comment by anthonynsimon** [comment]
Thanks! That'd be great, will let you know once the public server is up 👍

**Pull request merged**
